/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ahorcadoclient.Cliente;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author diego
 */
public class VistaJuego extends javax.swing.JFrame {
	private Cliente cliente;

	/**
	 * Creates new form VistaJuego
	 */
	public VistaJuego(Cliente cliente) {
		initComponents();
		
		this.cliente = cliente;

		JRootPane rootPane = SwingUtilities.getRootPane(enviarButton);
		rootPane.setDefaultButton(enviarButton);
		
		this.addWindowListener(new WindowAdapter(){
			@Override
			public void windowClosing(WindowEvent e){
				cliente.desconectarse();
				System.exit(0);
			}
		});
	}
	
	public Cliente getCliente()
	{
		return cliente;
	}
	
	public void nuevoJuego(){
		int vidas = cliente.getVidas();
		vidasTextLabel.setText("" + vidas); //! @todo arreglar esto
		
		String nombreJugador = cliente.getNombre();
		nombreJugadorTextLabel.setText("" + nombreJugador);
		
		int numLetras = cliente.getNumLetras();
		letrasNoValidasTextLabel.setText("<html>");
		palabrasNoValidasTextLabel.setText("<html>");
		
		palabraTextLabel.setText("");
		for (int i = 0; i < numLetras; ++i)
			palabraTextLabel.setText(palabraTextLabel.getText() + "_ ");
		
		cliente.iniciarEscuchaPartida(this);
	}
	
	public void actualizarPalabra(String palabraDescubierta){
		palabraTextLabel.setText("");
		for (int i = 0; i < palabraDescubierta.length(); ++i)
			palabraTextLabel.setText(palabraTextLabel.getText() + palabraDescubierta.charAt(i) + " ");
	}
	
	public void nuevaLetraNoValida(String letra){
		if (!letrasNoValidasTextLabel.getText().substring(6).contains(letra))
			letrasNoValidasTextLabel.setText(letrasNoValidasTextLabel.getText() + letra + ", ");
	}
	
	public void nuevaPalabraNoValida(String palabra){
		if (!palabrasNoValidasTextLabel.getText().contains(palabra + ","))
			palabrasNoValidasTextLabel.setText(palabrasNoValidasTextLabel.getText() + palabra + ", ");
	}
	
	public void actualizarVidas(String vidas){
		vidasTextLabel.setText(vidas);
	}
	
	public void terminarPartida(String adivinador, String palabra){
		JOptionPane.showMessageDialog(this, "¡" + adivinador + " ha adivinado la palabra! Era \"" + palabra + "\".");
		cliente.terminarPartida();
	}
	
	public void terminarPartida(String palabra){
		JOptionPane.showMessageDialog(this, "¡Habéis perdido! La palabra era \"" + palabra + "\".");
		cliente.terminarPartida();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vidasTextLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        palabraTextLabel = new javax.swing.JLabel();
        entradaLetrasTextField = new javax.swing.JTextField();
        enviarButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        letrasNoValidasTextLabel = new javax.swing.JLabel();
        palabrasNoValidasTextLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombreJugadorTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado Online - Hodgson Software");

        jLabel1.setText("Vidas: ");

        vidasTextLabel.setText("6");

        jLabel2.setText("Palabra: ");

        palabraTextLabel.setText("_ _ _");

        entradaLetrasTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entradaLetrasTextFieldActionPerformed(evt);
            }
        });

        enviarButton.setText("Proponer");
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Letras no válidas:");

        letrasNoValidasTextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        palabrasNoValidasTextLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel5.setText("Palabras no válidas:");

        jLabel4.setText("Jugador:");

        nombreJugadorTextLabel.setText("___");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(entradaLetrasTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enviarButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(palabraTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(letrasNoValidasTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(palabrasNoValidasTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vidasTextLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nombreJugadorTextLabel)))
                        .addGap(0, 371, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombreJugadorTextLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vidasTextLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(palabraTextLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(letrasNoValidasTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(palabrasNoValidasTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarButton)
                    .addComponent(entradaLetrasTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarButtonActionPerformed
        // Obtener la propuesta del jugador
		String propuesta = entradaLetrasTextField.getText().trim();
		
		if (propuesta.length() > 1){
			// La propuesta es una palabra completa
			cliente.proponerPalabra(propuesta);
		}
		else if (propuesta.length() == 1){
			// La propuesta es una letra
			cliente.proponerLetra(propuesta);
		}
		
		entradaLetrasTextField.setText("");
    }//GEN-LAST:event_enviarButtonActionPerformed

    private void entradaLetrasTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entradaLetrasTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entradaLetrasTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField entradaLetrasTextField;
    private javax.swing.JButton enviarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel letrasNoValidasTextLabel;
    private javax.swing.JLabel nombreJugadorTextLabel;
    private javax.swing.JLabel palabraTextLabel;
    private javax.swing.JLabel palabrasNoValidasTextLabel;
    private javax.swing.JLabel vidasTextLabel;
    // End of variables declaration//GEN-END:variables
}
